스티치 자기소개서
seller-lee/toward_woowabros pull request #3
Opened 2020-09-26 13:11 UTC by lxxjn0

잘 부탁드립니다 🤩

2020-09-26 13:52 UTC, jnsorn reviewed
굳굳 한바퀴 돌고 또 올게요~

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> +컴퓨터공학과로 진학하면서 프로그래밍을 접하게 되었고 흥미를 느끼게 되었습니다.
왜 컴공으로 진학하게 되었는지가 드러나면 좋을 것 같아요.

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> + 저는 대학교를 컴퓨터 공학으로 진학하였습니다. 학부 수업에서 처음 마주한 자료구조, 알고리즘과 같은 이론은 실생활에서도 유용하게 쓰일 수 있는 내용이었습니다. 이 이론들은 프로그래밍이란 것을 통해 구현할 수 있었습니다. 실제로 유용한 이론을 프로그램으로 만들 수 있다는 것을 알게 되면서, 프로그래밍에 흥미를 느끼게 되었습니다. 처음 접하는 프로그래밍은
학부에서 배운 이론이 무엇을 뜻하는지 조금 더 구체적으로 작성하면 좋을 것 같아요

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
```suggestion
 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는 이런 저에게 딱 맞는 직업이였습니다. 항상 성장하고자 노력합니다. 스스로가 노력하여 성장한 만큼 사람들로부터 인정받습니다. 누군가가 나를 선택하는 것이 아닌, 내가 무엇인가를 선택하는, 그것이 회사이던지 새로운 도전이라 하더라도, 사람이 개발자라 생각했습니다. 사회가 가지는 여러 문제를 무엇보다 사람들이 빠르고 효율적으로 해결하도록 돕는 능력을 갖춘 직업이라 생각했습니다. 이런 점들이 저를 개발자의 길로 이끌었습니다. 그리고 무엇보다도 스스로 공부를 해나가는 순간들이 재밌고 즐거워서 선택하게 되었습니다.
```

기회보단 직업이라는 단어가 더 어울릴 것 같습니다.

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> + 취업을 준비하는 시기가 다가오면서 저는 슬럼프에 빠졌었습니다. 지금 개발 공부를 하는 것이 옳은지, 아니면 다른 기업들을 지원하기 위해서 코딩테스트를 공부하고 CS 지식에 집중하는 것이 옳은지 혼란이 오기 시작했습니다. 주위에 여러 사람의 조언을 구하면서 우선 하던 개발 공부를 계속하기로 결정했습니다. 저는 자바를 올해 처음 접하고 꾸준히 쓰고는 있었지
굿굿

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> +### 4. 기술 경향을 파악하고 업무 역량을 강화하기 위한 본인의 학습 방법을 구체적으로 설명해주세요.
너 유튜브도 잘보는데 추가하면 좋을 듯 합니다. 테크채널 빠삭이

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> + 페어 프로그래밍을 원활히 돕기 위한 SUPP 서비스를 우아한테크코스 기간 동안 진행했습니다. 저는 프로젝트에 대한 기획과 설계를 진행할 때는 적극적으로 의견을 제안하며 참여했지만, 개발 단계로 넘어가면서 혼란을 겪었습니다. 개발 프로젝트를 처음 겪은 탓에 팀에서 어떤 역할을 해야 하는지, 어떻게 진행하고 어떻게 이바지해야 하는지 잘 모르고 헤맸습니다.
굿굿

2020-09-26 13:52 UTC, jnsorn commented on self_introduction/stitch.md
> +### 5. 지난 개발 프로젝트들의 아쉬운 점이 있었다면 무엇이고 개선 방안은 뭘까요?
개선되지 않은 아쉬운 점은 없나용? 다 개선된 것들이네요!

2020-09-26 14:03 UTC, kouz95 commented on self_introduction/stitch.md
> + 배움은 나누면 배가 된다고 생각합니다. 개발 공부를 하는 다양한 방법 중 저는 스터디를 통해 개발 실력을 늘려왔습니다. 스터디는 저 혼자서 공부하는 것이 아니고 다양한 사람들과 함께 공부하는 것입니다. 열의를 가지는 사람들과 함께 공부하면 스터디원들이 학습하는 모습을 통해 동기부여도 되고 시너지가 발생하는 것 같습니다. 또한, 각기 다른 경험을 한 사람
앞으로도 스터디를 통해 공부할것이다 라는 내용이 추가되면 좋을것 같아요.
우아한 테크코스라는 환경의 특수성때문에 스터디를 하게 된건 아닐까? 회사에서도 스터디를 이어 갈 것 인가? 에 대한 의문이 생기네요.

2020-09-26 14:05 UTC, kouz95 commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
`스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다.`
문장이 어떤걸 의미하는지 잘 모르겠어요!
스스로 노력하고 성장하는 만큼 인정 받을수 있는 사람이 되고 싶다는 뜻인가요?

2020-09-26 14:06 UTC, kouz95 commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
`개발자는 이런 저에게 딱 맞는 기회였습니다.`
문장이 어색하다고 느껴져요. 개발자 = 기회 로 다가오네요.

2020-09-26 14:08 UTC, kouz95 commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
`누군가가 나를 선택하는 것이 아닌, 내가 무엇인가를 선택하는, 그것이 회사이던지 새로운 도전이라 하더라도, 사람이 개발자라 생각했습니다.`
영문법에 어울리는 구조라고 느껴집니다. `내가 무엇인가를 선택하는 사람이 개발자라 생각했습니다.` 는 한문장인게 좋을것 같아요.

2020-09-26 14:51 UTC, begaonnuri requested changes
캐치티비의 힘인가... 대체로 잘쓴듯
굿굿

2020-09-26 14:51 UTC, begaonnuri commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
동의

2020-09-26 14:51 UTC, begaonnuri commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
```suggestion
 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는 이런 저에게 딱 맞는 기회였습니다. 항상 성장하고자 노력합니다. 스스로가 노력하여 성장한 만큼 사람들로부터 인정받습니다. 누군가가 나를 선택하는 것이 아닌, 내가 무엇인가를 선택하는, 그것이 회사이던지 새로운 도전이라 하더라도, 사람이 개발자라 생각했습니다. 사회에 있는 여러 문제를 무엇보다 사람들이 빠르고 효율적으로 해결하도록 돕는 능력을 갖춘 직업이라 생각했습니다. 이런 점들이 저를 개발자의 길로 이끌었습니다. 그리고 무엇보다도 스스로 공부를 해나가는 순간들이 재밌고 즐거워서 선택하게 되었습니다.
```

2020-09-26 14:51 UTC, begaonnuri commented on self_introduction/stitch.md
> +[지식의 확장은 호기심에서부터 시작된다]
소제목엔 문장보단 질문에 나온 예시처럼 키워드가 되는게 나을듯
호기심, 긍정적인 마인드, 커뮤니케이션 이런식으로

2020-09-26 15:00 UTC, joseph415 commented on self_introduction/stitch.md
> + 대학 졸업을 앞두고 앞으로의 미래를 고민하며 휴학을 했습니다. 저는 좋은 연봉을 주고 좋은 워라벨을 가진 직장을 가기 위해 공부하고 준비하는 취준생이 되기 싫었습니다. 저의 미래를 결정하는 길목에서 돈과 워라벨이 내가 나아갈 방향을 결정하는 이유가 되는 것이 싫었습니다. 스스로 노력하고 성장하는 만큼 선택하고 인정받는 사람이 되고 싶었습니다. 개발자는
스스로가 노력하여 성장한 만큼 사람들로부터 인정받는 이유랑 개발자가 되기로 한 목적을 일치시키면 될거 같아요 

마지막줄에 사회가 가지는 여러 문제를 무엇보다 사람들이 빠르고 효율적으로 해결하도록 돕는 능력을 갖춘 직업이라 생각했습니다. 이말이 어색합니다. 스스로 노력해성장하는 느낌과 동떨어져 보여요

2020-09-26 15:00 UTC, joseph415 commented on self_introduction/stitch.md
> + 개발자는 프로그래밍이라는 도구를 통해 문제를 해결하는 사람이라고 생각합니다. 세상에는 문제를 해결하는 다양한 사람들이 존재하고, 각자가 문제를 해결하는 데 사용하는 도구만 다를 뿐, 모두 같은 방향과 가치를 추구한다고 생각합니다. 이렇게 문제를 해결하는 사람으로서 가져야 할 덕목이 긍정적인 마인드라고 생각합니다. 해결해야 하는 문제 중에는 큰 힘을 들이
협업하면서 느낀 점은 새로운 의견이나 안건을 제안했을 때 '안 될 것 같은데', '이건 불가능해'와 같이 부정적인 말로 시작하는 사람과 일하는 것은 매우 힘들다는 것입니다.

매우 힘들다 라는 표현보다 해결하는 시간을 지연시킨다는 느낌을 주는게 일관성이 있어보여요  ㅎ

2020-09-26 15:00 UTC, joseph415 commented on self_introduction/stitch.md
> + 페어 프로그래밍을 원활히 돕기 위한 SUPP 서비스를 우아한테크코스 기간 동안 진행했습니다. 저는 프로젝트에 대한 기획과 설계를 진행할 때는 적극적으로 의견을 제안하며 참여했지만, 개발 단계로 넘어가면서 혼란을 겪었습니다. 개발 프로젝트를 처음 겪은 탓에 팀에서 어떤 역할을 해야 하는지, 어떻게 진행하고 어떻게 이바지해야 하는지 잘 모르고 헤맸습니다.
데모때 프론트에 대한 칭찬이 굉장히 많았다는것도 추가하면 이득일듯

2020-09-27 04:21 UTC, begaonnuri commented on self_introduction/stitch.md
> + 페어 프로그래밍을 원활히 돕기 위한 SUPP 서비스를 우아한테크코스 기간 동안 진행했습니다. 저는 프로젝트에 대한 기획과 설계를 진행할 때는 적극적으로 의견을 제안하며 참여했지만, 개발 단계로 넘어가면서 혼란을 겪었습니다. 개발 프로젝트를 처음 겪은 탓에 팀에서 어떤 역할을 해야 하는지, 어떻게 진행하고 어떻게 이바지해야 하는지 잘 모르고 헤맸습니다.
(클템) 인정

2020-09-28 03:24 UTC, merged