Subway
seller-lee/toward_woowabros pull request #4
Opened 2020-09-26 13:20 UTC by joseph415

bb 화이ㅣ티이

2020-09-26 14:16 UTC, kouz95 commented on self_introduction/subway.md
> +또 생에 첫 프로젝트를 하게 되면서 든 설렘과 첫 배포를 하고 플레이스토어에 내가 만든 어플이 올라왔을 때의 그 순간의 느낌을 잊을 수 가 없는 것 같습니다. 표현 못할 벅차오름과 그 동안 고생했던 팀원들의 머리속 이미지들이 주마등 처럼 스쳐갔습니다. 마음 속 깊은 곳에서 이런 마음을 끓어올리는 경험이 정말 갚지고 좋았습니다.
갚지고 -> 값지고

2020-09-26 14:18 UTC, kouz95 commented on self_introduction/subway.md
> +저는 꼭 이런 개발자가 되고싶습니다. 나를 필요로하고 같이 일을 하고싶은 같이 일을 해보고싶은 개발자가 되고싶습니다. 지금은 많이 부족하고 배워야할게 정말 산더미지만 노력한다면 꼭 저 순간이 올거라고 생각합니다.
`지금은 많이 부족하고 배워야할게 정말 산더미지만 노력한다면 꼭 저 순간이 올거라고 생각합니다.`
~ 한 순간은 (목표는) 힘든것이지만, ~의 이유로 노력을 할것이기 때문에 얻을수 있을 것이라고 믿는다.
의 흐름은 어떨까요?

2020-09-26 14:19 UTC, kouz95 commented on self_introduction/subway.md
> +잘못된 의견이라도 나를 통해 배워가고 싶은 것이 있겠구나 라는 생각을 하게 되더라고요. 그러고 나서 다음부터는 '의견을 자신있게 말해보자' 라는 생각을 했습니다. 그렇게 교육과정을 진행 해보니 정말 서로에게 배워가는 것이 많았습니다. 하지만 처음에는 배려한다는 생각에 상대방의 의견을 무조건 적으로 수용을 하였습니다. 하지만 이 또한 좋은 것만이 아니라고
`그렇게 교육과정을 진행 해보니 정말 서로에게 배워가는 것이 많았습니다.` 무엇을 배웠는지 예시로 나타낼수 있을까요?

2020-09-26 14:21 UTC, kouz95 commented on self_introduction/subway.md
> +잘못된 의견이라도 나를 통해 배워가고 싶은 것이 있겠구나 라는 생각을 하게 되더라고요. 그러고 나서 다음부터는 '의견을 자신있게 말해보자' 라는 생각을 했습니다. 그렇게 교육과정을 진행 해보니 정말 서로에게 배워가는 것이 많았습니다. 하지만 처음에는 배려한다는 생각에 상대방의 의견을 무조건 적으로 수용을 하였습니다. 하지만 이 또한 좋은 것만이 아니라고
`말해보자` 라 생각해서 배워가는게 많았는데, 사실 배려한다는 생각에 말은 했지만 상대방의 의견만 수용을 했던건가요?

2020-09-26 14:22 UTC, kouz95 commented on self_introduction/subway.md
> +개발자에게 완성된 코드를 만들어 내는것도 중요하지만 정말 중요한 것은 마감 기한안에 만들어내 는 것이구나 라는 생각이 들게 되었죠. 기한이 지나면 기회는 나라가는 것이니까요.
무슨 나라인가요?

2020-09-26 14:23 UTC, kouz95 commented on self_introduction/subway.md
> +그때 저는 이 두 책임감 모두 가져가려고 노력했습니다. 기한이 주어지면 진짜 내가 중요한 것이 무엇인지 생각하게 되니 핀트가 엇나갈 일이 점차 줄었습니다. 이렇게 되니 팀 코드 생산성도 좋아지고 여러모로 긍정적인 효과를 낳았습니다.
구체적으로 어떤 노력을 했나요?

2020-09-26 14:24 UTC, kouz95 commented on self_introduction/subway.md
> +저는 항상 제자리에 있었을 겁니다. 항상 누군가가 어떤 것을 알려주면 그걸 토대로 공부를 했고 테크코스에서도 강의나 미션에 대한 주요 개념을 알려줬기 때문에 그에 대한 것을 찾아 공부 했었습니다. 베이스가 없는 상태에서 처음 시작해보려니 큰 두려움이 있었습니다. 하지만 한번 도전해보니 역시 그 처음이 어렵지 그 다음부턴 빠른 학습이 되었습니다.
도전하게된 계기가 있나요?

2020-09-26 14:26 UTC, kouz95 commented on self_introduction/subway.md
> +<객체지향 사실과 오해>
자신이 어떤 부분에서 좋은 책이라고 느꼈는지에 대한 구체적인 사례가 없으니, 실제로 읽었나? 라는 생각이 듭니다.

2020-09-26 14:30 UTC, kouz95 commented on self_introduction/subway.md
> +우형에 입사하게 된다면 해당 경험을 바탕으로 계속해서 변하는 상황에 유연하게 대처하여 그 상황에 빠르게 적응해 좋은 프로덕트가 나올 수 있도록 노력하겠습니다.
이 문장이 필요한가요?

2020-09-26 14:40 UTC, jnsorn commented on self_introduction/subway.md
> +
시작한 경위에 대한 내용은 없어보이네요!

2020-09-26 14:40 UTC, jnsorn commented on self_introduction/subway.md
> +우선 프로그래밍에 대해 흥미를 느끼게 해준 가장 큰 요인 중 하나는 자료구조 프로그래밍 수업시간에 한 학기 동안 만들어본 주소록 프로그램입니다. 어떤 알고리즘을 사용하는지에 따라 프로그래밍에 효율성이 바뀌는 것에 많은 흥미를 느꼈고 내가 직접 계산했던 시간복잡도와 실제 프로그램에서 실행되는 속도가 일치하는지 보면서 내가 좋고 효율적인 코드를 만들어야 프로
마지막 문장에서 `효율성이 결정되는 것`이 어떤 감정을 일으켰고 그것이 `꿈으로 이어졌다`가 더욱 자연스러울 것 같아요.

2020-09-26 14:40 UTC, jnsorn commented on self_introduction/subway.md
> +또 학교 수강 신청과 시험 기간만 되면 학교의 사이버강의 사이트는 항상 서버가 폭주하고 터지는 경우가 많이 일어납니다. 이런 일이 있을 때마다 서버관리자는 어떻게 해야 서버가 터지지 않고 잘 돌아가게 할 수 있을까 생각을 하곤 했습니다. 학교에서 배우는 tcp/ip와 네트워크 프로그래밍을 배우면서 서버가 몰리게 되는 경우에 대해 이론적으로 배우곤 하지만
궁금증으로 인해 개발자의 길로 간다라는 논리가 조금 빈약해보입니다

2020-09-26 14:44 UTC, jnsorn reviewed
핵심 자체는 괜찮은 것 같습니다 맞춤법이나 중간중간 핀트가 어긋나는부분들(갑자기 툭 튀어나오는 문장들)을 중심으로 수정해보면 좋을 것 같습니다.

2020-09-26 14:44 UTC, jnsorn commented on self_introduction/subway.md
> +또한 국토종주를 통해 사람들과 고난과 힘든 상황 속에 있을 때 함께 화합하고 '꾸준히 노력하고 포기하지 않을 때' 아름답고 위대한 결과물이 나온다는 것을 배웠습니다.
6번 문항에 대한 답이 다 좋네요! 다만 요 문장은 국토종주와 함께 있는게 나을 것 같습니다

2020-09-26 15:01 UTC, joseph415 commented on self_introduction/subway.md
> +우형에 입사하게 된다면 해당 경험을 바탕으로 계속해서 변하는 상황에 유연하게 대처하여 그 상황에 빠르게 적응해 좋은 프로덕트가 나올 수 있도록 노력하겠습니다.
우형들어가고싶다고요 ㅠ

2020-09-26 15:14 UTC, begaonnuri requested changes
분량이 너무 많은것같은데
전반적으로 중복되는 문장을 압축하는게 좋을것같음

대체로 잘쓴듯 굿굿

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +
동의

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +저는 꼭 이런 개발자가 되고싶습니다. 나를 필요로하고 같이 일을 하고싶은 같이 일을 해보고싶은 개발자가 되고싶습니다. 지금은 많이 부족하고 배워야할게 정말 산더미지만 노력한다면 꼭 저 순간이 올거라고 생각합니다.
질문이 `프로그래밍을 시작한 경위와 본격적으로 투신하고 생업으로 삼기로 결정한 이야기를 해주세요.` 인데
답변은 `어떤 프로그래머가 되고싶은가요?` 인것같음

처음, 마지막문단을 빼거나 수정하는게 좋아보임

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +제가 생각하는 책임감에는 2가지가 있습니다. 이 두가지 모두 중요하다고 생각되는데요. 맡겨진 임무에 대한 책임감과 마감기한에 대한 책임감입니다.
> 이 두가지 모두 중요하다고 생각되는데요

없어도 될듯

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +팀 프로젝트를 하면서 이슈를 가져갔을 때 저는 완성품을 만들어왔지 가장 중요한 마감기한을 잘 지키지 못했었습니다.
```suggestion
라는 ****피드백을 많이 받았습니다. 하지만 마감기한은 잘 지켜지지 못했습니다.
```

중복되는 내용이라 간결하게 바꿔도 될듯

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +개발자에게 완성된 코드를 만들어 내는것도 중요하지만 정말 중요한 것은 마감 기한안에 만들어내 는 것이구나 라는 생각이 들게 되었죠. 기한이 지나면 기회는 나라가는 것이니까요.
ㅋㅋ

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +그때 저는 이 두 책임감 모두 가져가려고 노력했습니다. 기한이 주어지면 진짜 내가 중요한 것이 무엇인지 생각하게 되니 핀트가 엇나갈 일이 점차 줄었습니다. 이렇게 되니 팀 코드 생산성도 좋아지고 여러모로 긍정적인 효과를 낳았습니다.
> 핀트가 엇나갈 일이 

비문이라 `핵심을 놓치는 일이` 정도로 바꾸는ㄱ ㅔ좋을듯

2020-09-26 15:14 UTC, begaonnuri commented on self_introduction/subway.md
> +그러다 보니 Nginx 내구 설정에 대해서도 의문이 생기게 되었습니다.
내부

2020-09-26 15:33 UTC, lxxjn0 reviewed
추가적인 피드백을 글 정리 후 남기기로 합의봤습니다.
추후에 다시 달아두도록 할게요

2020-09-26 15:33 UTC, lxxjn0 commented on self_introduction/subway.md
> +저는 꼭 이런 개발자가 되고싶습니다. 나를 필요로하고 같이 일을 하고싶은 같이 일을 해보고싶은 개발자가 되고싶습니다. 지금은 많이 부족하고 배워야할게 정말 산더미지만 노력한다면 꼭 저 순간이 올거라고 생각합니다.
1. 프로그래밍을 시작한 경위가 없는 것 같아요. 작성하면 좋을 것 같아요.

2. 생업으로 삼기로 결정한 이유가 너무 많은 것 같아요. 본인이 생각하기에 핵심적인 이유 한두가지로 간결하게 압축해서 보여주는 것이 좋을 것 같아요

2020-09-27 06:46 UTC, joseph415 commented on self_introduction/subway.md
> +
우테코꺼 복사하다 보니 그리 됐네요 확인 :)

2020-09-27 06:46 UTC, joseph415 commented on self_introduction/subway.md
> +잘못된 의견이라도 나를 통해 배워가고 싶은 것이 있겠구나 라는 생각을 하게 되더라고요. 그러고 나서 다음부터는 '의견을 자신있게 말해보자' 라는 생각을 했습니다. 그렇게 교육과정을 진행 해보니 정말 서로에게 배워가는 것이 많았습니다. 하지만 처음에는 배려한다는 생각에 상대방의 의견을 무조건 적으로 수용을 하였습니다. 하지만 이 또한 좋은 것만이 아니라고
뭔가 이상하긴 하네요. 의견을 냈지만 상대의견에 반박은 하지 않았다는 겁니다.

2020-09-27 06:46 UTC, joseph415 commented on self_introduction/subway.md
> +개발자에게 완성된 코드를 만들어 내는것도 중요하지만 정말 중요한 것은 마감 기한안에 만들어내 는 것이구나 라는 생각이 들게 되었죠. 기한이 지나면 기회는 나라가는 것이니까요.
ㅋㅋ

2020-09-27 06:46 UTC, joseph415 commented on self_introduction/subway.md
> +저는 항상 제자리에 있었을 겁니다. 항상 누군가가 어떤 것을 알려주면 그걸 토대로 공부를 했고 테크코스에서도 강의나 미션에 대한 주요 개념을 알려줬기 때문에 그에 대한 것을 찾아 공부 했었습니다. 베이스가 없는 상태에서 처음 시작해보려니 큰 두려움이 있었습니다. 하지만 한번 도전해보니 역시 그 처음이 어렵지 그 다음부턴 빠른 학습이 되었습니다.
당신을 보니 나도 '잘' 해지고 싶었거든요.

2020-10-05 12:08 UTC, merged